export const semanticTokenVars = {
  backgrounds: {
    canvas: '--color-canvas',
    surface: '--color-surface',
    surfaceElevated: '--color-surface-elevated',
    surfaceContrast: '--color-surface-contrast',
  },
  text: {
    primary: '--text-primary',
    secondary: '--text-secondary',
    muted: '--text-muted',
    inverse: '--text-inverse',
  },
  accent: {
    primary: '--accent-primary',
    hover: '--accent-hover',
    pressed: '--accent-pressed',
    success: '--accent-success',
    warning: '--accent-warning',
    danger: '--accent-danger',
    focusRing: '--accent-focus-ring',
  },
  spacing: {
    1: '--space-1',
    2: '--space-2',
    3: '--space-3',
    4: '--space-4',
    5: '--space-5',
    6: '--space-6',
    7: '--space-7',
    8: '--space-8',
    9: '--space-9',
    10: '--space-10',
  },
  typography: {
    display: '--font-size-display',
    heading: '--font-size-h2',
    body: '--font-size-body',
    bodySmall: '--font-size-body-small',
    caption: '--font-size-caption',
    button: '--font-size-button',
    numeric: '--font-size-numeric',
  },
  radius: {
    control: '--radius-control',
    button: '--radius-button',
    panel: '--radius-panel',
    sheet: '--radius-sheet',
    pill: '--radius-pill',
  },
  borders: {
    subtle: '--border-subtle',
    strong: '--border-strong',
    active: '--border-active',
    contrast: '--border-contrast',
  },
  elevation: {
    panel: '--shadow-panel',
    raised: '--shadow-raised',
    focus: '--shadow-focus',
  },
  motion: {
    fast: '--motion-duration-fast',
    normal: '--motion-duration-normal',
    slow: '--motion-duration-slow',
    standardEase: '--motion-ease-standard',
    emphasizedEase: '--motion-ease-emphasized',
  },
  layers: {
    base: '--layer-base',
    raised: '--layer-raised',
    sticky: '--layer-sticky',
    overlay: '--layer-overlay',
    modal: '--layer-modal',
  },
} as const;

export type SemanticTokenVars = typeof semanticTokenVars;
